param([ValidateSet('Preflight','Apply')][string]$Mode='Preflight',[Parameter(Mandatory)][string]$AppRoot,[Parameter(Mandatory)][string]$WinSWSource,[Parameter(Mandatory)][string]$NodeExe,[Parameter(Mandatory)][string]$ConfigFile,[string]$RuntimeRoot,[string]$ReleaseBase,[string]$ServiceRoot,[string]$LogRoot,[string]$DataRoot,[switch]$RunReadiness,[switch]$PreserveFailedArtifacts,[switch]$Isolation,[string]$IsolationWinSwSha256)
$ErrorActionPreference='Stop'
$expected='05B82D46AD331CC16BDC00DE5C6332C1EF818DF8CEEFCD49C726553209B3A0DA'
function Get-Sha256([string]$Path){$stream=[IO.File]::OpenRead($Path);try{$sha=[Security.Cryptography.SHA256]::Create();try{return [BitConverter]::ToString($sha.ComputeHash($stream)).Replace('-','')}finally{$sha.Dispose()}}finally{$stream.Dispose()}}
function Set-FileSystemAclCompat {
 param([Parameter(Mandatory)][System.IO.FileSystemInfo]$Item,[Parameter(Mandatory)][System.Security.AccessControl.FileSystemSecurity]$Acl)
 # Windows PowerShell exposes instance methods; pwsh 7 removed them and
 # provides the static extension APIs. Detect the capability, never the version.
 if (@($Item.PSObject.Methods.Match('SetAccessControl')).Count -gt 0) { $Item.SetAccessControl($Acl); return }
 if ($Item -is [IO.DirectoryInfo]) { [IO.FileSystemAclExtensions]::SetAccessControl([IO.DirectoryInfo]$Item,[Security.AccessControl.DirectorySecurity]$Acl); return }
 [IO.FileSystemAclExtensions]::SetAccessControl([IO.FileInfo]$Item,[Security.AccessControl.FileSecurity]$Acl)
}
function Set-Acl([string]$Path,[bool]$Writable){$item=Get-Item -LiteralPath $Path -Force;if(($item.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne 0){throw "Reparse point is forbidden: $Path"};$acl=if($item-is[IO.DirectoryInfo]){New-Object Security.AccessControl.DirectorySecurity}else{New-Object Security.AccessControl.FileSecurity};$acl.SetAccessRuleProtection($true,$false);$inherit=if($item-is[IO.DirectoryInfo]){[Security.AccessControl.InheritanceFlags]'ContainerInherit,ObjectInherit'}else{[Security.AccessControl.InheritanceFlags]::None};$allow=[Security.AccessControl.AccessControlType]::Allow;$current=[Security.Principal.WindowsIdentity]::GetCurrent().User;foreach($p in @(@([Security.Principal.SecurityIdentifier]'S-1-5-18',[Security.AccessControl.FileSystemRights]::FullControl),@([Security.Principal.SecurityIdentifier]'S-1-5-32-544',[Security.AccessControl.FileSystemRights]::FullControl),@($current,[Security.AccessControl.FileSystemRights]::ReadAndExecute),@([Security.Principal.SecurityIdentifier]'S-1-5-19',$(if($Writable){[Security.AccessControl.FileSystemRights]::Modify}else{[Security.AccessControl.FileSystemRights]::ReadAndExecute})))){$acl.AddAccessRule((New-Object Security.AccessControl.FileSystemAccessRule($p[0],$p[1],$inherit,[Security.AccessControl.PropagationFlags]::None,$allow)))};Set-FileSystemAclCompat -Item $item -Acl $acl}
function Set-TreeAcl([string]$Path,[bool]$Writable){foreach($item in @((Get-Item -LiteralPath $Path -Force))+@(Get-ChildItem -LiteralPath $Path -Recurse -Force -ErrorAction SilentlyContinue)){if(Test-Path -LiteralPath $item.FullName){Set-Acl $item.FullName $Writable}}}
$effectiveWinSwHash=if($Isolation-and$IsolationWinSwSha256){$IsolationWinSwSha256}else{$expected};if($effectiveWinSwHash-notmatch'^[A-Fa-f0-9]{64}$'){throw 'WinSW SHA-256 input is invalid'};if($IsolationWinSwSha256-and-not$Isolation){throw 'Isolation WinSW hash override requires -Isolation'};if((Get-Sha256 $WinSWSource)-ne$effectiveWinSwHash.ToUpperInvariant()){throw 'WinSW SHA-256 mismatch'}
$root=(Resolve-Path -LiteralPath $AppRoot).Path;$tmp=$null;$releaseCreated=$false;$artifacts=@()
try{
 if($Mode-eq'Preflight'){$tmp=Join-Path $root ('.temp\worker preflight '+[guid]::NewGuid().ToString('N').Substring(0,8));$release=Join-Path $tmp 'worker-releases\release-worker-test';$services=Join-Path $tmp 'services';$logs=Join-Path $tmp 'logs';$data=Join-Path $tmp 'data';$config=Join-Path $tmp 'config\public-opinion.env';New-Item -ItemType Directory -Path $services,$logs,$data,(Split-Path -Parent $config) -Force|Out-Null;Set-Content -LiteralPath $config -Value "PORT=4320`n" -Encoding UTF8}else{foreach($p in @($RuntimeRoot,$ReleaseBase,$ServiceRoot,$LogRoot,$DataRoot,$ConfigFile)){if([string]::IsNullOrWhiteSpace($p)){throw 'Worker Apply requires runtime/release/service/log/data/config paths'}};$release=[IO.Path]::GetFullPath($RuntimeRoot);$base=[IO.Path]::GetFullPath($ReleaseBase).TrimEnd('\');if([IO.Path]::GetFullPath((Split-Path -Parent $release)).TrimEnd('\')-ne$base){throw 'Worker RuntimeRoot must be a direct child of ReleaseBase'};$services=[IO.Path]::GetFullPath($ServiceRoot);$logs=[IO.Path]::GetFullPath($LogRoot);$data=[IO.Path]::GetFullPath($DataRoot);$config=[IO.Path]::GetFullPath($ConfigFile);if(-not(Test-Path -LiteralPath $config -PathType Leaf)){throw 'Worker service config is missing'};if(((Get-Item -LiteralPath $config -Force).Attributes-band[IO.FileAttributes]::ReparsePoint)-ne 0){throw 'Worker service config must not be a reparse point'};New-Item -ItemType Directory -Path $base,$services,$logs,$data -Force|Out-Null}
 & (Join-Path $PSScriptRoot 'build-worker-release.ps1') -SourceRoot $root -RuntimeRoot $release
 $releaseCreated=$true
 $buildSha=Get-Sha256 (Join-Path $release 'package-worker-release-manifest.json')
 Copy-Item -LiteralPath $WinSWSource -Destination (Join-Path $services 'PublicOpinionWorker.exe')
 $artifacts+=Join-Path $services 'PublicOpinionWorker.exe'
 & (Join-Path $PSScriptRoot 'render-config.ps1') -SourceRoot $root -RuntimeRoot $release -NodeExe $NodeExe -OutputDirectory $services -LogRoot $logs -ConfigFile $config -DataRoot $data -WorkerBuildSha $buildSha -ServiceName PublicOpinionWorker
 $artifacts+=Join-Path $services 'PublicOpinionWorker.xml'
 [xml]$xml=Get-Content -Raw -LiteralPath (Join-Path $services 'PublicOpinionWorker.xml');if($xml.service.arguments-ne('"'+(Join-Path $release 'worker\src\worker.js')+'"')){throw 'Worker entry mismatch'}
 $envs=@{};foreach($e in $xml.service.env){$envs[[string]$e.name]=[string]$e.value};foreach($pair in @(@('WORKER_MODE','enabled'),@('BUILD_SHA',$buildSha),@('UNIFIED_SOURCE_SCHEDULER_MODE','enabled'),@('WORKER_INTERVAL_MS','60000'),@('PUBLIC_OPINION_SERVICE_MODE','1'),@('PUBLIC_OPINION_ENV_FILE',$config),@('Q1_DAILY_OUT_ROOT',$data),@('Q1_DAILY_LOCK_ROOT',(Join-Path $data 'locks')),@('WORKER_STATE_ROOT',(Join-Path $data 'state')),@('NODE_PATH',''),@('NODE_OPTIONS',''))){if($envs[$pair[0]]-ne$pair[1]){throw "Worker env mismatch: $($pair[0])"}}
 $workerLog=Join-Path $logs 'PublicOpinionWorker';$lockRoot=Join-Path $data 'locks';$stateRoot=Join-Path $data 'state';New-Item -ItemType Directory -Path $workerLog,$lockRoot,$stateRoot -Force|Out-Null
 Set-TreeAcl $release $false;Set-Acl $services $false;Set-Acl (Join-Path $services 'PublicOpinionWorker.exe') $false;Set-Acl (Join-Path $services 'PublicOpinionWorker.xml') $false;Set-Acl (Split-Path -Parent $config) $false;Set-Acl $config $false
 if($Mode-eq'Preflight'){Set-TreeAcl $logs $true;Set-TreeAcl $data $true}else{Set-Acl $logs $true;Set-TreeAcl $workerLog $true;Set-Acl $data $true;Set-TreeAcl $lockRoot $true;Set-TreeAcl $stateRoot $true}
 & node.exe (Join-Path $PSScriptRoot 'verify-worker-release.js') $release $root;if($LASTEXITCODE-ne 0){throw 'Worker release verification failed'}
 & node.exe --check (Join-Path $release 'worker\src\worker.js');if($LASTEXITCODE-ne 0){throw 'Worker entry syntax failed'}
 & python.exe -c "import pathlib; compile(pathlib.Path(__import__('sys').argv[1]).read_bytes(), __import__('sys').argv[1], 'exec')" (Join-Path $release 'scripts\q1_crawler.py');if($LASTEXITCODE-ne 0){throw 'Python crawler compile failed'}
 $validation=@{DeploymentRoot=$services;ReleaseRoot=$release;SourceRoot=$root;ConfigFile=$config;DataRoot=$data;LogRoot=$logs;TargetService='PublicOpinionWorker'}
 if($Mode-eq'Preflight'-or$Isolation){$validation.Preflight=$true}
 & (Join-Path $PSScriptRoot 'validate-artifacts.ps1') @validation
 if($RunReadiness){& node.exe (Join-Path $PSScriptRoot 'worker-readiness.js') $release $ConfigFile;if($LASTEXITCODE-ne 0){throw 'Worker database readiness failed'}}
 Write-Output "PASS: Worker $Mode preparation validated runtime, ACL, Node/Python dependencies, and read-only schema/lease/epoch admission contract"
}catch{if($Mode-eq'Apply'-and-not$PreserveFailedArtifacts){foreach($a in $artifacts){if(Test-Path -LiteralPath $a){Remove-Item -LiteralPath $a -Force}};if($releaseCreated){& (Join-Path $PSScriptRoot 'remove-worker-release.ps1') -ReleaseRoot $release -ReleaseBase $ReleaseBase -ServiceRoot $services}};throw}finally{if($Mode-eq'Preflight'-and(Test-Path -LiteralPath $tmp)){$resolved=(Resolve-Path -LiteralPath $tmp).Path;$safe=(Resolve-Path -LiteralPath (Join-Path $root '.temp')).Path.TrimEnd('\');if(-not$resolved.StartsWith("$safe\",[StringComparison]::OrdinalIgnoreCase)){throw 'unsafe cleanup'};& node.exe -e "require('node:fs').rmSync(process.argv[1],{recursive:true,force:true,maxRetries:3})" $resolved}}
