$ErrorActionPreference='Stop'
$root=(Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..\..\..')).Path
$temp=(Resolve-Path -LiteralPath (Join-Path $root '.temp')).Path.TrimEnd('\')
$fixture=Join-Path $temp ('v188 worker '+[guid]::NewGuid().ToString('N'))
$release=Join-Path $fixture 'release-worker-test'
function State { [pscustomobject]@{Listeners=@(Get-NetTCPConnection -State Listen -LocalPort 3001,3306,4320 -ErrorAction SilentlyContinue|Sort-Object LocalPort|%{"$($_.LocalPort):$($_.OwningProcess)"})-join',';Services=@(Get-Service PublicOpinionApi,PublicOpinionWorker -ErrorAction SilentlyContinue|%{"$($_.Name):$($_.Status)"})-join',';Tasks=@(Get-ScheduledTask -TaskName 'BigPlayer Last Night Overseas Daily 02','BigPlayer Q1 Daily 02','BigPlayer Keep Server Alive' -ErrorAction SilentlyContinue|Sort-Object TaskName|%{"$($_.TaskName):$($_.State)"})-join','}}
$before=State
try{
 New-Item -ItemType Directory -Path $fixture|Out-Null
 & (Join-Path $root 'scripts\windows-services\build-worker-release.ps1') -SourceRoot $root -RuntimeRoot $release
 & node.exe (Join-Path $root 'scripts\windows-services\verify-worker-release.js') $release $root
 foreach($p in @('worker\src\worker.js','server\src\runtimeEnv.js','scripts\q1_crawler.py','node_modules\mysql2\package.json','package-worker-release-manifest.json')){if(-not(Test-Path -LiteralPath (Join-Path $release $p)-PathType Leaf)){throw "missing $p"}}
 $expectedBuildSha=(Get-FileHash -Algorithm SHA256 -LiteralPath (Join-Path $release 'package-worker-release-manifest.json')).Hash
 $renderRoot=Join-Path $fixture 'render';$renderLogs=Join-Path $fixture 'logs';$renderData=Join-Path $fixture 'data';$renderConfig=Join-Path $fixture 'config\public-opinion.env';New-Item -ItemType Directory -Path $renderRoot,$renderLogs,$renderData,(Split-Path -Parent $renderConfig)-Force|Out-Null;Set-Content -LiteralPath $renderConfig -Value "PORT=4320`n" -Encoding UTF8
 & (Join-Path $root 'scripts\windows-services\render-config.ps1') -SourceRoot $root -RuntimeRoot $release -NodeExe (Join-Path $env:SystemRoot 'System32\where.exe') -OutputDirectory $renderRoot -LogRoot $renderLogs -ConfigFile $renderConfig -DataRoot $renderData -WorkerBuildSha $expectedBuildSha -ServiceName PublicOpinionWorker
 [xml]$rendered=Get-Content -Raw -LiteralPath (Join-Path $renderRoot 'PublicOpinionWorker.xml');$buildEnv=@($rendered.service.env|Where-Object{$_.name-eq'BUILD_SHA'});if($buildEnv.Count-ne 1-or [string]$buildEnv[0].value-ne$expectedBuildSha){throw 'Worker BUILD_SHA is not the release manifest hash'}
 foreach($p in @('server\src\app.js','worker\test','.env')){if(Test-Path -LiteralPath (Join-Path $release $p)){throw "forbidden $p"}}
 Add-Content -LiteralPath (Join-Path $release 'worker\src\worker.js') -Value '//tamper';$old=$ErrorActionPreference;try{$ErrorActionPreference='Continue';& node.exe (Join-Path $root 'scripts\windows-services\verify-worker-release.js') $release $root *> $null;$code=$LASTEXITCODE}finally{$ErrorActionPreference=$old};if($code-eq 0){throw 'tamper passed'}
 $install=Get-Content -Raw -LiteralPath (Join-Path $root 'scripts\windows-services\install-services.cmd');if($install-notmatch 'if /I "%TARGET%"=="PublicOpinionWorker" set "RELEASE_ID=worker-release-' -or $install-notmatch 'prepare-worker-preflight\.ps1" -Mode Apply' -or $install-notmatch ':worker_install_failure'){throw 'Worker release/apply/rollback gate missing'};$workerFailure=($install-split '(?im)^:worker_install_failure\s*$')[1]-split '(?im)^:account_failure\s*$'|Select-Object -First 1;if($workerFailure-match 'PublicOpinionApi'){throw 'Worker failure path may touch API'};if($workerFailure-match '(?i)(?:schtasks|legacy)'){throw 'Worker failure path may touch legacy tasks'}
 $validator=Get-Content -Raw -LiteralPath (Join-Path $root 'scripts\windows-services\validate-artifacts.ps1');if($validator-notmatch 'Unresolved placeholder remains in deployed Worker XML' -or $validator-notmatch 'Production Worker XML leaks a user/source path'){throw 'Worker production XML leakage gates missing'}
 $preparer=Get-Content -Raw -LiteralPath (Join-Path $root 'scripts\windows-services\prepare-worker-preflight.ps1');if($preparer-notmatch 'if\(\$Mode-eq''Preflight''\)\{Set-TreeAcl \$logs' -or $preparer-notmatch 'Set-Acl \$logs \$true;Set-TreeAcl \$workerLog'){throw 'Worker Apply ACL scope gate missing'}
 $readiness=Get-Content -Raw -LiteralPath (Join-Path $root 'scripts\windows-services\worker-readiness.js');if($readiness-notmatch 'assertUnifiedSchedulerSchemaReady' -or $readiness-notmatch 'SELECT\|SHOW' -or $readiness-notmatch "releaseRoot, 'server/src/runtimeEnv'"){throw 'release-local read-only readiness contract missing'}
 Write-Output 'PASS: Worker release closure, manifest, tamper rejection, and apply gate validated'
}finally{if(Test-Path -LiteralPath $fixture){$r=(Resolve-Path -LiteralPath $fixture).Path;if(-not$r.StartsWith("$temp\",[StringComparison]::OrdinalIgnoreCase)){throw 'unsafe cleanup'};& node.exe -e "require('node:fs').rmSync(process.argv[1],{recursive:true,force:true,maxRetries:3})" $r}}
$after=State;foreach($n in @('Listeners','Services','Tasks')){if($before.$n-ne$after.$n){throw "protected state changed: $n"}}
