USE ai_companion;

CREATE TABLE IF NOT EXISTS chat_message_scores (
  id                   INT AUTO_INCREMENT PRIMARY KEY,
  version_id           INT NOT NULL,
  session_id           INT NOT NULL,
  message_id           INT NOT NULL,
  user_message_id      INT NULL,
  score_status         VARCHAR(16) NOT NULL DEFAULT 'pending',
  score_source         VARCHAR(16) NOT NULL DEFAULT 'llm',
  total_score          DECIMAL(5,1) NULL,
  accuracy_score       TINYINT UNSIGNED NULL,
  relevance_score      TINYINT UNSIGNED NULL,
  completeness_score   TINYINT UNSIGNED NULL,
  safety_score         TINYINT UNSIGNED NULL,
  tone_score           TINYINT UNSIGNED NULL,
  grade                VARCHAR(8) NULL,
  risk_level           VARCHAR(16) NOT NULL DEFAULT 'low',
  risk_tags_json       JSON NULL,
  strengths_json       JSON NULL,
  issues_json          JSON NULL,
  summary              VARCHAR(512) NULL,
  raw_result_json      JSON NULL,
  review_status        VARCHAR(16) NOT NULL DEFAULT 'pending',
  review_score         DECIMAL(5,1) NULL,
  review_note          TEXT NULL,
  reviewed_by          INT NULL,
  reviewed_at          TIMESTAMP NULL,
  created_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_score_message (message_id),
  KEY idx_score_version_created (version_id, created_at),
  KEY idx_score_version_status (version_id, score_status, review_status),
  KEY idx_score_version_risk (version_id, risk_level),
  KEY idx_score_session (session_id, message_id),
  CONSTRAINT fk_score_version FOREIGN KEY (version_id) REFERENCES versions(id) ON DELETE CASCADE,
  CONSTRAINT fk_score_session FOREIGN KEY (session_id) REFERENCES chat_sessions(id) ON DELETE CASCADE,
  CONSTRAINT fk_score_message FOREIGN KEY (message_id) REFERENCES chat_messages(id) ON DELETE CASCADE,
  CONSTRAINT fk_score_user_message FOREIGN KEY (user_message_id) REFERENCES chat_messages(id) ON DELETE SET NULL,
  CONSTRAINT fk_score_review_user FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
