const test=require('node:test'),assert=require('node:assert/strict'),cp=require('node:child_process'),path=require('node:path'),fs=require('node:fs'),os=require('node:os'),crypto=require('node:crypto');const cli=path.resolve(__dirname,'../../../scripts/windows-services/worker-only-controlled-cutover.js');
test('controlled CLI preflight verifies fake inputs while real apply fails closed',()=>{let r=cp.spawnSync(process.execPath,[cli,'--preflight','--controller=fake'],{encoding:'utf8'});assert.equal(r.status,0);assert.match(r.stdout,/fake-read-only-preflight/);r=cp.spawnSync(process.execPath,[cli,'--apply'],{encoding:'utf8'});assert.equal(r.status,3);assert.match(r.stderr,/REAL_APPLY_UNAUTHORIZED/);});
test('authorized-shaped real apply cannot reach service control before its required inputs pass',()=>{const r=cp.spawnSync(process.execPath,[cli,'--apply','--controller=real','--confirm=single-use-test'],{encoding:'utf8',env:{...process.env,PUBLIC_OPINION_WORKER_CUTOVER_AUTHORIZED:'true',PUBLIC_OPINION_WORKER_CUTOVER_CONFIRM:'single-use-test'}});assert.equal(r.status,4);assert.match(r.stderr,/candidate-wrapper is required/);assert.doesNotMatch(r.stderr,/sc\.exe|PublicOpinionApi|3001/);});
for(const fault of ['', 'stop','install','start','readiness','rollback'])test(`CLI fake controller ${fault||'success'}`,()=>{const r=cp.spawnSync(process.execPath,[cli,'--apply','--controller=fake',`--fault=${fault}`],{encoding:'utf8'});assert.equal(r.status,0);assert.match(r.stdout,/"apiUnchanged":true/);assert.match(r.stdout,/"workerCalls":\[/);assert.doesNotMatch(r.stdout,/PublicOpinionApi|3001/);});
test('CLI fake controller preflight failure stops before transaction',()=>{const r=cp.spawnSync(process.execPath,[cli,'--apply','--controller=fake','--fault=preflight'],{encoding:'utf8'});assert.equal(r.status,4);assert.match(r.stderr,/preflight/);assert.doesNotMatch(r.stderr,/PublicOpinionApi|3001/);});
function digest(file){return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex').toUpperCase()}
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'po-cli-input-')),p=name=>path.join(root,name);for(const[name,value]of [['worker.exe','worker'],['worker.xml','worker-xml'],['PublicOpinionApi.exe','api'],['PublicOpinionApi.xml','api-xml'],['candidate.exe','candidate'],['candidate.xml','candidate-xml'],['public-opinion.env','PORT=4320\n']])fs.writeFileSync(p(name),value);fs.mkdirSync(p('worker/src'),{recursive:true});fs.writeFileSync(p('worker/src/worker.js'),"'use strict';\n");fs.writeFileSync(p('package-worker-release-manifest.json'),JSON.stringify({algorithm:'sha256',kind:'worker',files:[{path:'worker/src/worker.js',sha256:digest(p('worker/src/worker.js'))}]}));const snapshot={service:'PublicOpinionWorker',paths:{envFile:p('public-opinion.env')},sha256:{workerWrapper:digest(p('worker.exe')),workerXml:digest(p('worker.xml')),apiWrapper:digest(p('PublicOpinionApi.exe')),apiXml:digest(p('PublicOpinionApi.xml')),candidateManifest:digest(p('package-worker-release-manifest.json')),envFile:digest(p('public-opinion.env'))}};fs.writeFileSync(p('snapshot.json'),JSON.stringify(snapshot));return{root,p,args:['--apply','--controller=fake',`--candidate-wrapper=${p('candidate.exe')}`,`--candidate-xml=${p('candidate.xml')}`,`--candidate-release=${root}`,`--worker-wrapper=${p('worker.exe')}`,`--worker-xml=${p('worker.xml')}`,`--api-wrapper=${p('PublicOpinionApi.exe')}`,`--api-xml=${p('PublicOpinionApi.xml')}`,`--verified-snapshot=${p('snapshot.json')}`,'--',`--env-file=${p('public-opinion.env')}`,`--fake-pinned-winsw-sha=${digest(p('candidate.exe'))}`]}}
function runFixture(change){const q=fixture();try{change?.(q);return cp.spawnSync(process.execPath,[cli,...q.args],{encoding:'utf8'})}finally{fs.rmSync(q.root,{recursive:true,force:true})}}
test('CLI fake accepts the same verified artifact arguments used by a future real controller',()=>{const r=runFixture();assert.equal(r.status,0);assert.match(r.stdout,/"status":"PASS"/);assert.match(r.stdout,/"apiUnchanged":true/);});
test('CLI fake preflight uses the same verified artifact arguments and remains read-only',()=>{const r=runFixture(q=>q.args.splice(0,1,'--preflight'));assert.equal(r.status,0);assert.match(r.stdout,/fake-read-only-preflight/);assert.match(r.stdout,/"apiUnchanged":true/);});
test('CLI permits fixed API observer arguments but rejects API deployment intent before input processing',()=>{let r=runFixture(q=>q.args.splice(1,0,`--api-target=${q.p('PublicOpinionApi.exe')}`));assert.equal(r.status,5);assert.match(r.stderr,/WORKER_ONLY_TARGET_REJECTED/);r=cp.spawnSync(process.execPath,[cli,'--preflight','--controller=fake','--service=PublicOpinionApi'],{encoding:'utf8'});assert.equal(r.status,5);assert.match(r.stderr,/WORKER_ONLY_TARGET_REJECTED/);});
test('CLI fake rejects an altered verified snapshot before cutover',()=>{const r=runFixture(q=>{const s=JSON.parse(fs.readFileSync(q.p('snapshot.json'),'utf8'));s.sha256.apiXml='0'.repeat(64);fs.writeFileSync(q.p('snapshot.json'),JSON.stringify(s));});assert.equal(r.status,4);assert.match(r.stderr,/verified-snapshot hash mismatch: api-xml/);});
test('CLI fake rejects a candidate hash that is not the pinned input hash',()=>{const r=runFixture(q=>q.args[q.args.findIndex(value=>value.startsWith('--fake-pinned-winsw-sha='))]='--fake-pinned-winsw-sha='+'0'.repeat(64));assert.equal(r.status,4);assert.match(r.stderr,/candidate-wrapper SHA-256 mismatch/);});
test('CLI requires the exact snapshotted service env-file and never uses an implicit process env',()=>{let r=runFixture(q=>q.args[q.args.findIndex(value=>value.startsWith('--env-file='))]='--env-file=');assert.equal(r.status,4,r.stderr);assert.match(r.stderr,/env-file is required/);r=runFixture(q=>{fs.writeFileSync(q.p('outside.env'),'PORT=4320\n');q.args[q.args.findIndex(value=>value.startsWith('--env-file='))]=`--env-file=${q.p('outside.env')}`});assert.equal(r.status,4,r.stderr);assert.match(r.stderr,/env-file does not match the verified service environment file/);});
test('CLI rejects missing, directory, reparse, and altered service env-files',()=>{let r=runFixture(q=>{fs.rmSync(q.p('public-opinion.env'));});assert.equal(r.status,4,r.stderr);assert.match(r.stderr,/env-file must be a non-reparse regular file/);r=runFixture(q=>{fs.rmSync(q.p('public-opinion.env'));fs.mkdirSync(q.p('public-opinion.env'));});assert.equal(r.status,4,r.stderr);assert.match(r.stderr,/env-file must be a non-reparse regular file/);r=runFixture(q=>{fs.writeFileSync(q.p('public-opinion.env'),'PORT=4321\n');});assert.equal(r.status,4,r.stderr);assert.match(r.stderr,/verified-snapshot hash mismatch: env-file/);});
test('CLI rejects an env-file reparse point before it can be used for readiness',()=>{const r=runFixture(q=>{const target=q.p('real.env'),link=q.p('env-link.env');fs.renameSync(q.p('public-opinion.env'),target);fs.symlinkSync(target,link,'file');q.args[q.args.findIndex(value=>value.startsWith('--env-file='))]=`--env-file=${link}`;const snapshot=JSON.parse(fs.readFileSync(q.p('snapshot.json'),'utf8'));snapshot.paths.envFile=link;snapshot.sha256.envFile=digest(target);fs.writeFileSync(q.p('snapshot.json'),JSON.stringify(snapshot));});assert.equal(r.status,4,r.stderr);assert.match(r.stderr,/env-file must be a non-reparse regular file/);});
test('Windows PowerShell 5.1 isolated B command preserves the explicit env-file after Node option parsing',()=>{const q=fixture();try{q.args[0]='--preflight';const quoted=q.args.map(value=>`'${value.replaceAll("'","''")}'`).join(',');const script=q.p('invoke-b.ps1');fs.writeFileSync(script,`$arguments=@(${quoted})\n& $env:PO_NODE $env:PO_CLI @arguments\nexit $LASTEXITCODE\n`);const r=cp.spawnSync('powershell.exe',['-NoProfile','-File',script],{encoding:'utf8',env:{...process.env,PO_NODE:process.execPath,PO_CLI:cli}});assert.equal(r.status,0,r.stderr);assert.match(r.stdout,/fake-read-only-preflight/);}finally{fs.rmSync(q.root,{recursive:true,force:true});}});
test('isolated readiness is limited to fake read-only preflight',()=>{const r=cp.spawnSync(process.execPath,[cli,'--apply','--controller=fake','--isolation-readiness'],{encoding:'utf8'});assert.equal(r.status,4,r.stderr);assert.match(r.stderr,/isolation-readiness requires fake read-only preflight/);});
test('CLI accepts a single UTF-8 BOM emitted by Windows PowerShell 5.1 for a verified snapshot',()=>{const r=runFixture(q=>{const text=fs.readFileSync(q.p('snapshot.json'),'utf8');const write=cp.spawnSync('powershell.exe',['-NoProfile','-Command','[IO.File]::WriteAllText($env:PO_SNAPSHOT_FILE, $env:PO_SNAPSHOT_TEXT, [Text.UTF8Encoding]::new($true))'],{encoding:'utf8',env:{...process.env,PO_SNAPSHOT_FILE:q.p('snapshot.json'),PO_SNAPSHOT_TEXT:text}});assert.equal(write.status,0,write.stderr);assert.deepEqual([...fs.readFileSync(q.p('snapshot.json')).subarray(0,3)],[0xEF,0xBB,0xBF]);});assert.equal(r.status,0);assert.match(r.stdout,/"status":"PASS"/);});
test('CLI rejects a verified snapshot with two UTF-8 BOM signatures',()=>{const r=runFixture(q=>{const bytes=fs.readFileSync(q.p('snapshot.json'));fs.writeFileSync(q.p('snapshot.json'),Buffer.concat([Buffer.from([0xEF,0xBB,0xBF,0xEF,0xBB,0xBF]),bytes]));});assert.equal(r.status,4);assert.match(r.stderr,/verified-snapshot must be valid JSON/);});
test('CLI rejects UTF-16, malformed JSON, and structurally incomplete snapshots',()=>{for(const body of [Buffer.concat([Buffer.from([0xFF,0xFE]),Buffer.from('{"service":"PublicOpinionWorker"}','utf16le')]),Buffer.from('{not-json','utf8'),Buffer.from('{"service":"PublicOpinionWorker","sha256":{}}','utf8')]){const r=runFixture(q=>fs.writeFileSync(q.p('snapshot.json'),body));assert.equal(r.status,4);assert.match(r.stderr,/verified-snapshot (must be valid JSON|hash mismatch)/);}});
