$ErrorActionPreference='Stop';$root=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path;$script=Join-Path $root 'scripts\windows-services\prepare-taptap-worker-candidate.ps1';$text=Get-Content -Raw $script
foreach($n in @('prepare-worker-preflight.ps1','PreserveFailedArtifacts=$true','verified-snapshot.json','ExpectedPackageLockSha256','PackageLockSource','package lock hash mismatch','candidate ID already exists','C_B_UNAUTHORIZED','PUBLIC_OPINION_STAGE_C_B_CONFIRM','PublicOpinionWorker','PublicOpinionApi','GitGate')){if($text-notmatch[regex]::Escape($n)){throw "missing gate: $n"}}
if($text-match'install-services\.cmd|rollback-services\.cmd'){throw 'Stage C cannot invoke service-control scripts'}
$preparer=Get-Content -Raw (Join-Path $root 'scripts\windows-services\prepare-worker-preflight.ps1');if($preparer-notmatch'\[switch\]\$PreserveFailedArtifacts'-or$preparer-notmatch'-and-not\$PreserveFailedArtifacts'-or$preparer-notmatch'Isolation WinSW hash override requires -Isolation'){throw 'candidate evidence preservation/isolation boundary missing'}
$tmp=Join-Path ([IO.Path]::GetTempPath()) ('po-stage-c-'+[guid]::NewGuid().ToString('N'));try{
 $repo=Join-Path $tmp 'repo';$app=Join-Path $repo 'bigPlayer\public-opinion-system';$data=Join-Path $tmp 'data';New-Item -ItemType Directory -Path $app,(Join-Path $data 'services') -Force|Out-Null;Set-Location $repo;& git init -q;& git config user.email test@example.invalid;& git config user.name test
 New-Item -ItemType Directory -Path (Join-Path $app 'worker\src') -Force|Out-Null;Set-Content (Join-Path $app 'worker\src\worker.js') "'use strict';";Set-Content (Join-Path $app 'package-lock.json') '{"lockfileVersion":3}';$lockSha=(Get-FileHash (Join-Path $app 'package-lock.json') -Algorithm SHA256).Hash;& git add bigPlayer/public-opinion-system/worker/src/worker.js bigPlayer/public-opinion-system/package-lock.json;& git commit -qm baseline;$baseline=(& git rev-parse HEAD).Trim()
 Add-Content (Join-Path $app 'worker\src\worker.js') "// TapTap checkpoint cursor";& git commit -am candidate -q;$candidate=(& git rev-parse HEAD).Trim();$patch=(& git diff --binary "$baseline..$candidate"|Out-String);$patchSha=([BitConverter]::ToString(([Security.Cryptography.SHA256]::Create()).ComputeHash([Text.Encoding]::UTF8.GetBytes($patch)))).Replace('-','')
 foreach($n in @('PublicOpinionWorker.exe','PublicOpinionApi.exe','PublicOpinionApi.xml')){Set-Content (Join-Path $data "services\$n") $n};Set-Content (Join-Path $data 'config.env') 'X=1';$configPath=(Join-Path $data 'config.env');$workerXml='<service><env name="PUBLIC_OPINION_ENV_FILE" value="'+[Security.SecurityElement]::Escape($configPath)+'" /></service>';Set-Content -LiteralPath (Join-Path $data 'services\PublicOpinionWorker.xml') -Value $workerXml -Encoding utf8;Set-Content (Join-Path $data 'winsw.exe') 'isolated winsw';$winSha=(Get-FileHash (Join-Path $data 'winsw.exe') -Algorithm SHA256).Hash
 $a=@('-NoProfile','-ExecutionPolicy','Bypass','-File',$script,'-Mode','DryRun','-Isolation','-ProgramDataRoot',$data,'-CandidateId','worker-release-taptap-contract-20260920','-SourceRoot',$app,'-WinSWSource',(Join-Path $data 'winsw.exe'),'-NodeExe','node.exe','-ConfigFile',(Join-Path $data 'config.env'),'-ExpectedBaselineCommit',$baseline,'-ExpectedCandidateCommit',$candidate,'-ExpectedTapTapPatchSha256',$patchSha,'-ExpectedPackageLockSha256',$lockSha,'-PackageLockSource',(Join-Path $app 'package-lock.json'),'-IsolationWinSwSha256',$winSha);& powershell @a;if($LASTEXITCODE-ne 0){throw 'isolated dry-run failed'}
 $wrongLock=$a.Clone();$wrongLock[([array]::IndexOf($wrongLock,$lockSha))]='0'*64;$oldPreference=$ErrorActionPreference;$ErrorActionPreference='Continue';& powershell @wrongLock 2>$null;$wrongLockExit=$LASTEXITCODE;$ErrorActionPreference=$oldPreference;if($wrongLockExit -eq 0){throw 'wrong package-lock hash did not fail'}
 $unauthorized=@('-NoProfile','-ExecutionPolicy','Bypass','-File',$script,'-Mode','Prepare','-CandidateId','worker-release-taptap-contract-20260920','-SourceRoot',$app,'-WinSWSource',(Join-Path $data 'winsw.exe'),'-NodeExe','node.exe','-ConfigFile',(Join-Path $data 'config.env'),'-ExpectedBaselineCommit',$baseline,'-ExpectedCandidateCommit',$candidate,'-ExpectedTapTapPatchSha256',$patchSha,'-ExpectedPackageLockSha256',$lockSha,'-PackageLockSource',(Join-Path $app 'package-lock.json'));$oldPreference=$ErrorActionPreference;$ErrorActionPreference='Continue';$unauthorizedOutput=((& powershell @unauthorized 2>&1|ForEach-Object {"$_"})-join"`n");$unauthorizedExit=$LASTEXITCODE;$ErrorActionPreference=$oldPreference;if($unauthorizedExit -eq 0 -or $unauthorizedOutput -notmatch 'C_B_UNAUTHORIZED'){throw 'real Prepare did not fail closed before ProgramData writes'}
 $override=@($unauthorized + @('-CAndBConfirm','test-confirm','-IsolationWinSwSha256',$winSha));$oldAuth=$env:PUBLIC_OPINION_STAGE_C_B_AUTHORIZED;$oldConfirm=$env:PUBLIC_OPINION_STAGE_C_B_CONFIRM;$env:PUBLIC_OPINION_STAGE_C_B_AUTHORIZED='true';$env:PUBLIC_OPINION_STAGE_C_B_CONFIRM='test-confirm';$oldPreference=$ErrorActionPreference;$ErrorActionPreference='Continue';$overrideOutput=((& powershell @override 2>&1|ForEach-Object {"$_"})-join"`n");$overrideExit=$LASTEXITCODE;$ErrorActionPreference=$oldPreference;$env:PUBLIC_OPINION_STAGE_C_B_AUTHORIZED=$oldAuth;$env:PUBLIC_OPINION_STAGE_C_B_CONFIRM=$oldConfirm;if($overrideExit -eq 0 -or $overrideOutput -notmatch 'Isolation WinSW hash override requires -Isolation'){throw 'production hash override was not rejected'}
 $a[([array]::IndexOf($a,'DryRun'))]='Prepare';$a+=@('-Fault','hash');& powershell @a;if($LASTEXITCODE-eq 0){throw 'isolated hash fault did not fail'};if(-not(Test-Path (Join-Path $data 'audit\worker-release-taptap-contract-20260920\failure.json'))){throw 'failed candidate evidence was not retained'}
}finally{Set-Location $root;if(Test-Path $tmp){Remove-Item -LiteralPath $tmp -Force -Recurse}}
Write-Output 'PASS: Stage C contract keeps candidate-only writes, snapshots, and failure evidence'
