'use strict';
const { BaseConnector, ConnectorError, ConnectorPageError, ConnectorPageResult, normalizeRawContent, validatePagination } = require('./baseConnector');
const DEFAULT_BASE_URL = 'https://discord.com/api/v10';
const DISCORD_SNOWFLAKE = /^\d{15,22}$/;
const MAX_CHANNEL_IDS = 50;
function enabled(value) { return value === 'true' || value === '1'; }
function parseConfig(source = {}) {
  let config = source.config;
  if (typeof config === 'string') { try { config = JSON.parse(config); } catch { config = {}; } }
  config = config && typeof config === 'object' ? config : {};
  const guildId = String(config.guildId || config.guild_id || '').trim();
  const values = Array.isArray(config.channelIds || config.channel_ids) ? (config.channelIds || config.channel_ids) : String(config.channelIds || config.channel_ids || '').split(/[,，\n\r]+/);
  const channelIds = [...new Set(values.map(value => String(value || '').trim()).filter(value => DISCORD_SNOWFLAKE.test(value)))].slice(0, MAX_CHANNEL_IDS);
  return { ...config, guildId, channelIds, channelScope: String(config.channelScope || config.channel_scope || 'selected').trim().toLowerCase() === 'all_accessible' ? 'all_accessible' : 'selected', includeThreads: config.includeThreads === true, includeReplies: config.includeReplies !== false, anonymizeAuthors: config.anonymizeAuthors === true };
}
function decodeCursor(value) {
  if (value == null || value === '') return { version: 1, channelIndex: 0, before: null, channelIds: null };
  try { const parsed = JSON.parse(String(value)); const channelIndex = Number(parsed.channelIndex); const before = parsed.before == null || parsed.before === '' ? null : String(parsed.before); if ((parsed.version === 1 || parsed.version === 2) && Number.isInteger(channelIndex) && channelIndex >= 0 && (before == null || DISCORD_SNOWFLAKE.test(before))) { const channelIds = parsed.version === 2 && Array.isArray(parsed.channelIds) ? parsed.channelIds.map(item => String(item || '').trim()).filter(item => DISCORD_SNOWFLAKE.test(item)) : null; if (parsed.version === 2 && !channelIds?.length) throw new Error('empty snapshot'); return { version: parsed.version, channelIndex, before, channelIds }; } } catch {}
  throw new ConnectorError('INVALID_PAGINATION', 'Discord pagination cursor is invalid');
}
function authorName(author, { anonymizeAuthors = false } = {}) { const id = String(author?.id || '').trim(); if (anonymizeAuthors) return id ? `discord-user-${id.slice(-8)}` : 'discord-user'; return String(author?.global_name || author?.username || '').trim(); }
function messageUrl(guildId, channelId, messageId) { return `https://discord.com/channels/${guildId}/${channelId}/${messageId}`; }
function normalizeMessage(message, { guildId, channelId, config } = {}) {
  const id = String(message?.id || '').trim(); if (!DISCORD_SNOWFLAKE.test(id)) throw new ConnectorError('MALFORMED_RESPONSE', 'Discord message id is required');
  const referenceId = String(message?.message_reference?.message_id || '').trim(); const threadParentId = String(message?.thread?.id ? message?.id : '').trim(); const contentType = referenceId ? 'comment' : 'post'; const attachments = Array.isArray(message?.attachments) ? message.attachments : []; const reactions = Array.isArray(message?.reactions) ? message.reactions : [];
  const normalized = normalizeRawContent({ externalId: id, contentType, title: '', body: String(message?.content || '').trim(), authorName: authorName(message?.author, config), publishedAt: message?.timestamp || null, sourceUrl: messageUrl(guildId, channelId, id), engagement: { reactions: reactions.reduce((total, reaction) => total + Math.max(0, Number(reaction?.count) || 0), 0), replies: Number(message?.message_reference ? 1 : 0), attachments: attachments.length }, media: attachments.map(item => item?.url).filter(Boolean) });
  return { ...normalized, platformAuthorId: message?.author?.id == null ? null : String(message.author.id), rootPlatformContentId: contentType === 'comment' ? (referenceId || threadParentId || id) : '', platformParentId: contentType === 'comment' ? referenceId || null : null, contentDepth: contentType === 'comment' ? 1 : 0, isDeleted: false };
}
function publicAuthReason(code) { return { UNAUTHORIZED: 'DISCORD_TOKEN_INVALID', PERMISSION_DENIED: 'DISCORD_SCOPE_FORBIDDEN', DISCORD_RESOURCE_NOT_FOUND: 'DISCORD_SCOPE_NOT_FOUND', NO_ACCESSIBLE_TEXT_CHANNELS: 'DISCORD_NO_ACCESSIBLE_CHANNELS', RATE_LIMITED: 'DISCORD_RATE_LIMITED' }[code] || code || 'DISCORD_AUTH_CHECK_FAILED'; }
class DiscordConnector extends BaseConnector {
  constructor(env = process.env, { fetchImpl = globalThis.fetch, credentialContext = null } = {}) { super({ platform: 'discord', capabilities: ['posts', 'owned_content', 'comments', 'threads'] }); this.enabled = enabled(String(env.DISCORD_ENABLED || '').toLowerCase()); this.baseUrl = String(env.DISCORD_API_BASE_URL || DEFAULT_BASE_URL).replace(/\/$/, ''); this.allowedHosts = new Set(String(env.DISCORD_ALLOWED_HOSTS || 'discord.com').split(',').map(value => value.trim().toLowerCase()).filter(Boolean)); this.timeoutMs = Math.max(1000, Number(env.DISCORD_TIMEOUT_MS || 15000)); this.pageLimit = Math.min(100, Math.max(1, Number(env.DISCORD_PAGE_LIMIT || 100))); this.fetchImpl = fetchImpl; this.credentialContext = credentialContext; }
  hostAllowed(url = this.baseUrl) { let parsed; try { parsed = new URL(url); } catch { return false; } return parsed.protocol === 'https:' && !parsed.username && !parsed.password && !parsed.hash && (!parsed.port || parsed.port === '443') && this.allowedHosts.has(parsed.hostname.toLowerCase()); }
  async installationHealth() { const installed = this.enabled && this.hostAllowed(this.baseUrl); return { platform: this.platform, installed, configured: installed, reason: installed ? null : (this.enabled ? 'official Discord API host is required' : 'disabled by configuration'), capabilities: this.capabilities }; }
  async api(path, { token, params = {}, capability = 'posts', page = 1, signal } = {}) {
    const endpoint = new URL(path, `${this.baseUrl}/`); if (!this.hostAllowed(endpoint.toString())) throw new ConnectorError('URL_OUTSIDE_ALLOWED_HOSTS', 'Discord request host is not allowed'); for (const [key, value] of Object.entries(params)) if (value != null && value !== '') endpoint.searchParams.set(key, String(value));
    let response; try { response = await this.fetchImpl(endpoint, { headers: { accept: 'application/json', authorization: `Bot ${token}` }, signal: signal || AbortSignal.timeout(this.timeoutMs) }); } catch (error) { throw new ConnectorPageError(this.platform, capability, page, error); }
    if (!response.ok) { let retryAfterMs = null; if (response.status === 429) { try { const payload = await response.json(); retryAfterMs = Math.max(0, Number(payload?.retry_after || 0) * 1000); } catch {} } const code = response.status === 401 ? 'UNAUTHORIZED' : response.status === 403 ? 'PERMISSION_DENIED' : response.status === 404 ? 'DISCORD_RESOURCE_NOT_FOUND' : response.status === 429 ? 'RATE_LIMITED' : `DISCORD_HTTP_${response.status}`; const cause = new ConnectorError(code, `Discord API request failed with status ${response.status}`, retryAfterMs == null ? {} : { retryAfterMs }); const error = new ConnectorPageError(this.platform, capability, page, cause); if (retryAfterMs != null) error.retryAfterMs = retryAfterMs; throw error; }
    try { return await response.json(); } catch { throw new ConnectorPageError(this.platform, capability, page, new ConnectorError('MALFORMED_RESPONSE', 'Discord API returned invalid JSON')); }
  }
  async tokenFor({ account, credentialContext } = {}) { const context = credentialContext || this.credentialContext; if (!context) throw new ConnectorError('CREDENTIAL_CONTEXT_REQUIRED', 'Discord credential context is required'); const token = String(await context.loadApiToken(account, 'api_token') || '').trim().replace(/^Bot\s+/i, ''); if (!token) throw new ConnectorError('CREDENTIAL_SECRET_EMPTY', 'Discord account credential is empty'); return token; }
  async accessibleGuildChannelIds({ guildId, token, signal } = {}) { const channels = await this.api(`guilds/${encodeURIComponent(guildId)}/channels`, { token, capability: 'authorization', signal }); if (!Array.isArray(channels)) throw new ConnectorError('MALFORMED_RESPONSE', 'Discord guild channels response must be an array'); return [...new Set(channels.filter(channel => [0, 5].includes(Number(channel?.type))).map(channel => String(channel?.id || '').trim()).filter(channelId => DISCORD_SNOWFLAKE.test(channelId)))].sort(); }
  async accountHealth({ source, account, credentialContext, signal } = {}) { const installation = await this.installationHealth(); if (!installation.installed) return { ...installation, authorized: false }; const config = parseConfig(source || {}); if (!DISCORD_SNOWFLAKE.test(config.guildId) || (config.channelScope === 'selected' && !config.channelIds.length)) return { ...installation, authorized: false, configured: false, reason: 'Discord guildId and channel scope are required' }; let token; try { token = await this.tokenFor({ account, credentialContext }); } catch (error) { return { ...installation, authorized: false, configured: false, reason: error.code || 'CREDENTIAL_NOT_FOUND' }; } try { await this.api('users/@me', { token, capability: 'authorization', signal }); await this.api(`guilds/${encodeURIComponent(config.guildId)}`, { token, capability: 'authorization', signal }); const channelIds = config.channelScope === 'all_accessible' ? await this.accessibleGuildChannelIds({ guildId: config.guildId, token, signal }) : config.channelIds; if (!channelIds.length) return { ...installation, authorized: false, configured: false, reason: 'NO_ACCESSIBLE_TEXT_CHANNELS' }; if (config.channelScope === 'selected') for (const channelId of channelIds) await this.api(`channels/${encodeURIComponent(channelId)}`, { token, capability: 'authorization', signal }); return { ...installation, authorized: true, configured: true, reason: null }; } catch (error) { const reason = error.cause?.code || error.code || 'DISCORD_AUTH_CHECK_FAILED'; return { ...installation, authorized: false, configured: false, reason: publicAuthReason(reason) }; }
  }
  async healthCheck(context) { const health = await this.accountHealth(context); return { platform: this.platform, configured: health.configured, reason: health.reason }; }
  async detectCapabilities(context = {}) { const health = await this.accountHealth(context); const status = health.authorized ? 'authorized_scope' : 'unauthorized'; return Object.fromEntries(this.capabilities.map(capability => [capability, { status, reason: health.reason || null }])); }
  hasSourceCapability(capability, source) { const config = parseConfig(source); if (capability === 'comments') return config.includeReplies; if (capability === 'threads') return config.includeThreads; return this.hasCapability(capability); }
  async listOwnedContents({ source, account, credentialContext, cursor, limit, signal } = {}) {
    const installation = await this.installationHealth(); if (!installation.installed) throw new ConnectorError('CONNECTOR_NOT_CONFIGURED', installation.reason || 'Discord connector is not installed'); const config = parseConfig(source); if (!DISCORD_SNOWFLAKE.test(config.guildId) || (config.channelScope === 'selected' && !config.channelIds.length)) throw new ConnectorError('CONNECTOR_NOT_CONFIGURED', 'Discord source requires a guildId and channel scope'); const current = decodeCursor(cursor); const token = await this.tokenFor({ account, credentialContext }); const channelIds = current.channelIds || (config.channelScope === 'all_accessible' ? await this.accessibleGuildChannelIds({ guildId: config.guildId, token, signal }) : config.channelIds); if (!channelIds.length) throw new ConnectorError('NO_ACCESSIBLE_TEXT_CHANNELS', 'Discord guild has no accessible text or announcement channels'); if (current.channelIndex >= channelIds.length) throw new ConnectorError('INVALID_PAGINATION', 'Discord channel cursor is out of range'); const channelId = channelIds[current.channelIndex]; const pageSize = Math.min(this.pageLimit, Math.max(1, Number(limit) || this.pageLimit)); const messages = await this.api(`channels/${encodeURIComponent(channelId)}/messages`, { token, params: { limit: pageSize, ...(current.before ? { before: current.before } : {}) }, capability: 'owned_content', page: current.before ? 2 : 1, signal }); if (!Array.isArray(messages)) throw new ConnectorError('MALFORMED_RESPONSE', 'Discord messages response must be an array'); const items = messages.filter(message => !String(message?.message_reference?.message_id || '').trim()).map(message => normalizeMessage(message, { guildId: config.guildId, channelId, config })); const oldestId = String(messages.at(-1)?.id || '').trim() || null; const hasMoreInChannel = messages.length >= pageSize && oldestId && oldestId !== current.before; const cursorVersion = current.channelIds || config.channelScope === 'all_accessible' ? 2 : 1; const cursorFields = cursorVersion === 2 ? { version: 2, channelIds } : { version: 1 }; const nextCursor = hasMoreInChannel ? JSON.stringify({ ...cursorFields, channelIndex: current.channelIndex, before: oldestId }) : (current.channelIndex + 1 < channelIds.length ? JSON.stringify({ ...cursorFields, channelIndex: current.channelIndex + 1, before: null }) : null); return validatePagination({ cursor, limit, page: new ConnectorPageResult({ items, nextCursor, hasMore: nextCursor != null, capability: 'authorized_scope', raw: messages }) });
  }
  async listPosts(input) { return this.listOwnedContents(input); }
  async listComments({ source, account, credentialContext, cursor, limit, signal, postId, rootContentId } = {}) {
    const installation = await this.installationHealth();
    if (!installation.installed) throw new ConnectorError('CONNECTOR_NOT_CONFIGURED', installation.reason || 'Discord connector is not installed');
    const config = parseConfig(source);
    if (!DISCORD_SNOWFLAKE.test(config.guildId) || (config.channelScope === 'selected' && !config.channelIds.length)) throw new ConnectorError('CONNECTOR_NOT_CONFIGURED', 'Discord source requires a guildId and channel scope');
    const targetId = String(postId || rootContentId || '').trim();
    if (!DISCORD_SNOWFLAKE.test(targetId)) throw new ConnectorError('INVALID_CONTENT_ID', 'Discord comment collection requires a post id');
    const current = decodeCursor(cursor);
    const token = await this.tokenFor({ account, credentialContext });
    const channelIds = current.channelIds || (config.channelScope === 'all_accessible' ? await this.accessibleGuildChannelIds({ guildId: config.guildId, token, signal }) : config.channelIds);
    if (!channelIds.length) throw new ConnectorError('NO_ACCESSIBLE_TEXT_CHANNELS', 'Discord guild has no accessible text or announcement channels');
    if (current.channelIndex >= channelIds.length) throw new ConnectorError('INVALID_PAGINATION', 'Discord channel cursor is out of range');
    const channelId = channelIds[current.channelIndex];
    const pageSize = Math.min(this.pageLimit, Math.max(1, Number(limit) || this.pageLimit));
    const messages = await this.api(`channels/${encodeURIComponent(channelId)}/messages`, { token, params: { limit: pageSize, ...(current.before ? { before: current.before } : {}) }, capability: 'comments', page: current.before ? 2 : 1, signal });
    if (!Array.isArray(messages)) throw new ConnectorError('MALFORMED_RESPONSE', 'Discord messages response must be an array');
    const items = messages.filter(message => String(message?.message_reference?.message_id || '').trim() === targetId).map(message => normalizeMessage(message, { guildId: config.guildId, channelId, config }));
    const oldestId = String(messages.at(-1)?.id || '').trim() || null;
    const hasMoreInChannel = messages.length >= pageSize && oldestId && oldestId !== current.before;
    const cursorVersion = current.channelIds || config.channelScope === 'all_accessible' ? 2 : 1;
    const cursorFields = cursorVersion === 2 ? { version: 2, channelIds } : { version: 1 };
    const nextCursor = hasMoreInChannel ? JSON.stringify({ ...cursorFields, channelIndex: current.channelIndex, before: oldestId }) : (current.channelIndex + 1 < channelIds.length ? JSON.stringify({ ...cursorFields, channelIndex: current.channelIndex + 1, before: null }) : null);
    return validatePagination({ cursor, limit, page: new ConnectorPageResult({ items, nextCursor, hasMore: nextCursor != null, capability: 'comments', raw: messages }) });
  }
}
module.exports = { DiscordConnector, DEFAULT_BASE_URL, DISCORD_SNOWFLAKE, MAX_CHANNEL_IDS, parseConfig, decodeCursor, normalizeMessage };
